//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisV2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 50")]
        public global::System.Drawing.Point PosInd1 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd1"]));
            }
            set {
                this["PosInd1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd2 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd2"]));
            }
            set {
                this["PosInd2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd3 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd3"]));
            }
            set {
                this["PosInd3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd4 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd4"]));
            }
            set {
                this["PosInd4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd5 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd5"]));
            }
            set {
                this["PosInd5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd6 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd6"]));
            }
            set {
                this["PosInd6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd7 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd7"]));
            }
            set {
                this["PosInd7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd8 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd8"]));
            }
            set {
                this["PosInd8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd9 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd9"]));
            }
            set {
                this["PosInd9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd10 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd10"]));
            }
            set {
                this["PosInd10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd11 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd11"]));
            }
            set {
                this["PosInd11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd12 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd12"]));
            }
            set {
                this["PosInd12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd13 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd13"]));
            }
            set {
                this["PosInd13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd14 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd14"]));
            }
            set {
                this["PosInd14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd15 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd15"]));
            }
            set {
                this["PosInd15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd16 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd16"]));
            }
            set {
                this["PosInd16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd17 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd17"]));
            }
            set {
                this["PosInd17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd18 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd18"]));
            }
            set {
                this["PosInd18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd19 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd19"]));
            }
            set {
                this["PosInd19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PosInd20 {
            get {
                return ((global::System.Drawing.Point)(this["PosInd20"]));
            }
            set {
                this["PosInd20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.1")]
        public string IpAdres {
            get {
                return ((string)(this["IpAdres"]));
            }
            set {
                this["IpAdres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] ActPosInd {
            get {
                return ((int[])(this["ActPosInd"]));
            }
            set {
                this["ActPosInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] Mem1PosInd {
            get {
                return ((int[])(this["Mem1PosInd"]));
            }
            set {
                this["Mem1PosInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] Mem2PosInd {
            get {
                return ((int[])(this["Mem2PosInd"]));
            }
            set {
                this["Mem2PosInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] Mem3PosInd {
            get {
                return ((int[])(this["Mem3PosInd"]));
            }
            set {
                this["Mem3PosInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] Mem4PosInd {
            get {
                return ((int[])(this["Mem4PosInd"]));
            }
            set {
                this["Mem4PosInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] Mem5PosInd {
            get {
                return ((int[])(this["Mem5PosInd"]));
            }
            set {
                this["Mem5PosInd"] = value;
            }
        }
    }
}
